const getData = () => {
    return [
      {
        id: 1,
        title: "Front End Development Libraries",
        date: "01 July 2023",
        issuer: "FreeCodeCamp",
        imageUrl: "/images/sertifikat/FrontEndDevelopmentLibraries.png",
        link: "https://www.freecodecamp.org/certification/farhanadityaa/front-end-development-libraries",
      },
      {
        id: 2,
        title: "JavaScript Algorithms and Data Structures",
        date: "1 July 2023",
        issuer: "FreeCodeCamp",
        imageUrl: "images/sertifikat/JavaScriptAlgorithmsandDataStructures.png",
        link: "https://www.freecodecamp.org/certification/farhanadityaa/javascript-algorithms-and-data-structures",
      },
      {
        id: 3,
        title: "Java Foundations",
        date: "16 April 2022",
        issuer: "Oracle Academy",
        imageUrl: "images/sertifikat/JavaFoundations.png",
        link: "https://drive.google.com/file/d/1c0itDRTh_JJ8T0C-BkHrdZ0b9VJOFMC5/view",
      },
      {
        id: 4,
        title: "Fullstack Developer",
        date: "30 Juni 2023",
        issuer: "MSIB x Citiasia",
        imageUrl: "images/sertifikat/MSIB4.png",
        link: "https://drive.google.com/file/d/1k9dKz9uiGnNqekBL2_lWCxA7dz4vEEyD/view?usp=sharing",
      },
      {
        id: 5,
        title: "Belajar Membuat Aplikasi Android Pemula",
        date: "9 September 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/android-beginner.png",
        link: "https://www.dicoding.com/certificates/GRX52KDRVX0M",
      },
      {
        id: 6,
        title: "Basic Programming",
        date: "21 Agustus 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/basic-programming.png",
        link: "https://www.dicoding.com/certificates/KEXL0RD2WPG2",
      },
      {
        id: 7,
        title: "Pemrograman Kotlin",
        date: "30 Agustus 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/start-kotlin.png",
        link: "https://www.dicoding.com/certificates/98XWVW6J0PM3",
      },
      {
        id: 8,
        title: "Pengenalan ke Logika Pemrograman",
        date: "21 Agustus 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/logic-programming.png",
        link: "https://www.dicoding.com/certificates/6RPNWL299P2M",
      },
      {
        id: 9,
        title: "Belajar Dasar Github",
        date: "23 Agustus 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/basic-github.png",
        link: "https://www.dicoding.com/certificates/2VX3JGYDQPYQ",
      },
      {
        id: 10,
        title: "Prinsip Pemrograman Solid",
        date: "8 Oktober 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/prinsip-solid.png",
        link: "https://www.dicoding.com/certificates/98XWVO11LPM3",
      },
      {
        id: 11,
        title: "Belajar Fundamental Aplikasi Android",
        date: "1 Desember 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/fundamental-android.png",
        link: "https://www.dicoding.com/certificates/1OP8NDJL8XQK",
      },
      {
        id: 12,
        title: "Pengembangan Android Intermediate",
        date: "11 Desember 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/android-intermediate.png",
        link: "https://www.dicoding.com/certificates/MRZM8DQY3ZYQ",
      },
      {
        id: 13,
        title: "Prinsip Pemrograman Solid",
        date: "12 Desember 2023",
        issuer: "Dicoding",
        imageUrl: "images/sertifikat/jetpack-compose.png",
        link: "https://www.dicoding.com/certificates/GRX5QL0RYZ0M",
      },
    ];
  };
  
  export { getData };
  